# Generated by Django 2.2.3 on 2019-07-15 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('url', models.URLField(blank=True, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=300)),
                ('checksum', models.CharField(max_length=35)),
            ],
        ),
        migrations.AddField(
            model_name='garment',
            name='images',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Image'),
        ),
    ]
